---
awx_exposed_http_port: 3003
awx_internal_http_port: 80

awx_image_link: quay.io/ansible/awx
awx_image_version: 21.13.0
awx_container_name: awx

awx_redis_image: docker.io/library/redis
awx_redis_tag: 7.0.9

awx_postgres_image_name: postgres
awx_postgres_image_version: 13
awx_postgres_image_link: "docker.io/{{ awx_postgres_image_name }}"

awx_nginx_image_version: 1.23.3
awx_nginx_image_link: docker.io/nginx

awx_coredns_image_link: docker.io/coredns/coredns
awx_coredns_image_version: 1.10.1
coredns_internal_port: 53
coredns_external_port: 1053

postgres_port: 5432
# rabbitmq_port: 5672
# memcached_port: 11211

awx_port: 8052

awx_hashicorp_vault_image_version: 1.12
awx_hashicorp_vault_image_link: docker.io/hashicorp/vault
awx_hashicorp_vault_external_port: 8200
awx_hashicorp_vault_internal_port: 8200

awx_hashicorp_consul_image_version: 1.13
awx_hashicorp_consul_image_link: docker.io/hashicorp/consul
awx_hashicorp_consul_internal_port: 8500

awx_secret_key: mysecretkey
awx_database_user: awx
awx_database_password: "{{ awx_postgres_auth_password }}"
awx_database_name: awx
awx_database_port: "{{ postgres_port }}"
awx_database_host: awx_postgres
awx_allowed_hosts: localhost,127.0.0.1
awx_timezone: UTC