  - name: Generate an SSH key for the current user
    ansible.builtin.user:
      generate_ssh_key: yes
      name: "{{ current_user | default(ansible_user, true) }}"
    register: keygen
    notify:
    - restart sshd

  - name: Display generated PUBLIC key
    debug:
      var: keygen.ssh_public_key
