---
- name: Ensure user systemd config directory exists
  file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    recurse: true
    state: directory

- name: Copy the plasmashell systemd service file
  template:
    src: plasmashell.service.j2
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/plasmashell.service"
    mode: 0644
  notify:
  - restart plasmashell