---
- name: Install gnupg
  pacman:
    name: gnupg
    state: present

- name: Enable gpg-agent.socket
  systemd:
    name: gpg-agent.socket
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ ansible_env.USER }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_id }}"

- name: Enable dirmngr.socket
  systemd:
    name: dirmngr.socket
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ ansible_env.USER }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_id }}"

- name: Enable gpg-agent-ssh.socket
  systemd:
    name: gpg-agent-ssh.socket
    scope: user
    enabled: yes
    state: started
  become: yes
  become_user: "{{ ansible_env.USER }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_id }}"

