#https://github.com/bevyengine/bevy/blob/main/docs/linux_dependencies.md
#sudo pacman -S libx11 pkgconf alsa-lib
#Install pipewire-alsa or pulseaudio-alsa depending on the sound server you are using.
#Depending on your graphics card, you may have to install one of the following: vulkan-radeon, vulkan-intel, or mesa-vulkan-drivers

- name: Ensure pkgconfig is installed
  include_role:
    name: korbad.arch.pkg_config
  when: ansible_distribution == 'Archlinux'

- name: Install Bevy dependencies for Arch variants
  community.general.pacman:
    name:
      - libx11
      - alsa-lib
  become: true

- name: Ensure audio codecs are set up
  include_role:
    name: audio_codecs
